version: '3.7'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=geospace
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - geospacedb:/var/lib/postgresql/data
  web:
    build: . 
    volumes:
      - .:/code/
    ports:
      - 4242:4242
    command: bash -c "./run.sh"
    depends_on:
      - db
    restart: on-failure
volumes:
  geospacedb:
