version: '3.7'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=total
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - geospacedb:/var/lib/postgresql/data
  web:
    build: docker/
    volumes:
      - .:/code/
    ports:
      - 7070:7070
    command: bash -c "run.sh"
    depends_on:
      - db
    restart: on-failure
volumes:
  geospace:
